// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1xlz0hJFk8t0s0eMjs-Bce0wc7LKRk8',
    appId: '1:609632342920:web:feccb908a6fdc6d452e03d',
    messagingSenderId: '609632342920',
    projectId: 'rapidito-12a67',
    authDomain: 'rapidito-12a67.firebaseapp.com',
    storageBucket: 'rapidito-12a67.firebasestorage.app',
    measurementId: 'G-MSG6XZVX25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyL2aAFz8NWyhl229Nh6fb9nHPOLo_qM',
    appId: '1:609632342920:android:ba74d30ea06661a952e03d',
    messagingSenderId: '609632342920',
    projectId: 'rapidito-12a67',
    storageBucket: 'rapidito-12a67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqEMq6d5C1WOCuivgL_d04yO3Ad9U0cc',
    appId: '1:609632342920:ios:0877a4508cba082952e03d',
    messagingSenderId: '609632342920',
    projectId: 'rapidito-12a67',
    storageBucket: 'rapidito-12a67.firebasestorage.app',
    iosBundleId: 'com.example.rapidito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfqEMq6d5C1WOCuivgL_d04yO3Ad9U0cc',
    appId: '1:609632342920:ios:0877a4508cba082952e03d',
    messagingSenderId: '609632342920',
    projectId: 'rapidito-12a67',
    storageBucket: 'rapidito-12a67.firebasestorage.app',
    iosBundleId: 'com.example.rapidito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1xlz0hJFk8t0s0eMjs-Bce0wc7LKRk8',
    appId: '1:609632342920:web:8607506479e9776e52e03d',
    messagingSenderId: '609632342920',
    projectId: 'rapidito-12a67',
    authDomain: 'rapidito-12a67.firebaseapp.com',
    storageBucket: 'rapidito-12a67.firebasestorage.app',
    measurementId: 'G-K8734RRBWL',
  );
}
